# Generated by Django 4.2.5 on 2023-09-28 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Filter",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("verbose_name", models.CharField(max_length=200)),
                ("filter_type", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Provider",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("region", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("okpd2", models.CharField(max_length=24, null=True)),
                ("name", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True, null=True)),
                ("link_to_source", models.CharField(max_length=200, null=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
                ("source", models.CharField(max_length=200, null=True)),
                (
                    "provider",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="indexing.provider"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FilterValue",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("value", models.CharField(max_length=200)),
                ("filter", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="indexing.filter")),
                ("item", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="indexing.item")),
            ],
        ),
    ]
