# Generated by Django 4.2.5 on 2023-09-28 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("indexing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="link_to_source",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="okpd2",
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="provider",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="indexing.provider"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="source",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
