# Generated by Django 4.2.5 on 2023-09-29 08:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("indexing", "0004_alter_item_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="lemma_name",
            field=models.CharField(blank=True, null=True),
        ),
    ]
