# Generated by Django 4.2.5 on 2023-09-29 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("indexing", "0005_item_lemma_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="provider",
            name="inn",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="provider",
            name="kapital",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="provider",
            name="registration_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="provider",
            name="region",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
