# Generated by Django 4.2.5 on 2023-09-29 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("indexing", "0006_provider_inn_provider_kapital_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="provider",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
