# Generated by Django 4.2.5 on 2023-09-29 15:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("indexing", "0007_alter_provider_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filter",
            name="verbose_name",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
