# Generated by Django 4.2.5 on 2023-09-30 08:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("indexing", "0008_alter_filter_verbose_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="provider",
            name="okved",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="provider",
            name="rusprofile_link",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="provider",
            name="rusprofile_negative",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="provider",
            name="rusprofile_positive",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="provider",
            name="type",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="provider",
            name="registration_date",
            field=models.CharField(blank=True, null=True),
        ),
    ]
