# Generated by Django 4.2.5 on 2023-09-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("indexing", "0010_alter_provider_kapital"),
    ]

    operations = [
        migrations.AlterField(
            model_name="provider",
            name="region",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
