# Generated by Django 4.2.5 on 2023-09-30 11:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("indexing", "0012_filterrange"),
    ]

    operations = [
        migrations.RenameField(
            model_name="filterrange",
            old_name="okved",
            new_name="okpd2",
        ),
    ]
