# Generated by Django 4.2.5 on 2023-09-30 13:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("indexing", "0013_rename_okved_filterrange_okpd2"),
    ]

    operations = [
        migrations.AddField(
            model_name="filterrange",
            name="values_amount",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
