# Generated by Django 4.2.5 on 2023-10-01 08:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("indexing", "0015_provider_address_provider_release"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyFiltersByOKPD",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "types",
                    django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None),
                ),
                ("min_kap", models.IntegerField()),
                ("max_kap", models.IntegerField()),
            ],
        ),
    ]
