# Generated by Django 4.2.5 on 2023-10-01 08:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("indexing", "0016_companyfiltersbyokpd"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyfiltersbyokpd",
            name="okpd",
            field=models.CharField(blank=True, null=True),
        ),
    ]
