# Generated by Django 4.2.5 on 2023-10-01 08:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("indexing", "0017_companyfiltersbyokpd_okpd"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyfiltersbyokpd",
            name="max_kap",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="companyfiltersbyokpd",
            name="min_kap",
            field=models.CharField(),
        ),
    ]
