# Generated by Django 4.2.5 on 2023-10-01 10:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("indexing", "0018_alter_companyfiltersbyokpd_max_kap_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Answer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("question_text", models.TextField()),
                ("suggested_okpd", models.CharField(max_length=100)),
            ],
        ),
    ]
