# Generated by Django 4.2.5 on 2023-11-04 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("indexing", "0021_answer_items"),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "sentiment",
                    models.CharField(
                        choices=[("positive", "positive"), ("neutral", "neutral"), ("negative", "negative")],
                        max_length=100,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("author", models.CharField(choices=[("user", "user"), ("bot", "bot")], max_length=100)),
                ("message", models.CharField(max_length=1000)),
                ("lemmatization_message", models.CharField(max_length=1000)),
                ("stop_theme", models.CharField(max_length=100, null=True)),
                (
                    "conversation",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="indexing.conversation"),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="answer",
            name="items",
        ),
        migrations.DeleteModel(
            name="CompanyFiltersByOKPD",
        ),
        migrations.RemoveField(
            model_name="filterrange",
            name="filter",
        ),
        migrations.RemoveField(
            model_name="filtervalue",
            name="filter",
        ),
        migrations.RemoveField(
            model_name="filtervalue",
            name="item",
        ),
        migrations.RemoveField(
            model_name="item",
            name="provider",
        ),
        migrations.DeleteModel(
            name="Answer",
        ),
        migrations.DeleteModel(
            name="Filter",
        ),
        migrations.DeleteModel(
            name="FilterRange",
        ),
        migrations.DeleteModel(
            name="FilterValue",
        ),
        migrations.DeleteModel(
            name="Item",
        ),
        migrations.DeleteModel(
            name="Provider",
        ),
    ]
