# Generated by Django 4.2.5 on 2023-11-04 18:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("indexing", "0022_conversation_message_remove_answer_items_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="sequence_number",
            field=models.IntegerField(null=True),
        ),
    ]
