# Generated by Django 4.2.5 on 2023-11-04 18:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("indexing", "0023_message_sequence_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="lemmatization_message",
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
