# Generated by Django 4.2.5 on 2023-11-05 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("indexing", "0024_alter_message_lemmatization_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="can_promote",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="conversation",
            name="sentiment_score",
            field=models.IntegerField(default=0),
        ),
    ]
