# Generated by Django 4.2.5 on 2023-11-06 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("indexing", "0026_alter_conversation_sentiment_score"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coords",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "type",
                    models.CharField(
                        choices=[("stop_theme", "stop_theme"), ("sentiment", "sentiment")], max_length=100
                    ),
                ),
                ("x", models.DecimalField(decimal_places=2, max_digits=10)),
                ("y", models.DecimalField(decimal_places=2, max_digits=10)),
                ("label", models.CharField(max_length=100)),
                ("message", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="indexing.message")),
            ],
        ),
    ]
