# Generated by Django 4.2.5 on 2023-11-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("indexing", "0027_coords"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="stop_theme",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
